config/routes.rb
NCBlog::Application.routes.draw do

  post "/users" => "homes#create"
  resources :homes do
      resources :users
      resources :articles do
      resources :comments
    end
    resources :photo_albums do
      resources :photos
    end
    resources :message_boards
  end
  get "ajax/update_dressup"
  post "ajax/login"
  get "ajax/logout"
  get "ajax/verification_username"
  post "ajax/pa_edit"
  post "ajax/edit_cover"

   root :to => 'homes#index'

end

app/models/message_board.rb
class MessageBoard < ActiveRecord::Base
  belongs_to :home
  belongs_to :user

  def self.return_current_page_message_boards(home_id, page)
    return MessageBoard.limit(10).offset((page.to_i-1)*10).order("created_at Desc").find_all_by_home_id(home_id)
  end

  def self.count_page(home_id)
    length = MessageBoard.order("created_at Desc").find_all_by_home_id(home_id).count()
    if length>10
      page_temp=length%10
      if page_temp==0
        always_page =length/10
      else
        always_page= length/10+1
      end
    else
      always_page=1
    end
    return always_page
  end

  def self.return_reply_message_board(message_board)
     if message_board.is_reply
       return mb=MessageBoard.find_by_id(message_board.message_id);
     end
    false
  end

end

app/controllers/message_boards_controller.rb
class MessageBoardsController < ApplicationController
  layout "show_home"
  before_filter :initialization_parameter_and_admin
  before_filter :initialization_parameter, :except => [:create, :destroy]
  # GET /message_boards
  # GET /message_boards.json
  def index
    @home_id = params[:home_id]
    params[:page] ? @page =  params[:page] : @page = 1
    @message_boards = MessageBoard.return_current_page_message_boards(@home_id, @page)
    @always_page = MessageBoard.count_page(@home_id)

  end


  # POST /message_boards
  # POST /message_boards.json
  def create
    info = params[:info]
    @home_id = params[:home_id]
    mb=MessageBoard.new(info: info, home_id: @home_id, user_id: session[:user].id);
    redirect_to home_message_boards_path(@home_id) if mb.save
   end

  # PUT /message_boards/1
  # PUT /message_boards/1.json
  def update
    @message_board = MessageBoard.find(params[:id])

    respond_to do |format|
      if @message_board.update_attributes(params[:message_board])
        format.html { redirect_to @message_board, notice: 'Message board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message_board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_boards/1
  # DELETE /message_boards/1.json
  def destroy
    @message_board = MessageBoard.find(params[:id])
     @message_board.destroy  if @is_admin
    redirect_to home_message_boards_path(@current_home)
  end

  private
  def  initialization_parameter_and_admin
    @current_home=Home.find_by_id(params[:home_id])
    if @current_home
      @current_user = @current_home.user
      @is_admin=true if session[:user] && session[:user].id==@current_user.id
    else
      redirect_to homes_path
    end
  end

  def  initialization_parameter
    @dressups=Dressup.all();
    @current_dressup = @current_home.dressup
  end
end

app/helpers/message_boards_helper.rb
module MessageBoardsHelper
end

app/views/message_boards/create.html.erb
<script type="text/javascript">
    alert("提交失败！")
    location.href="<%=home_message_boards_path(@home_id)%>"
</script>

app/views/message_boards/index.html.erb
<%=render  partial: 'homes/style_css'%>
<div class="bg_img">
  <p class="module_title">
    留言板
  </p>
  <div>
    <table>
      <%for message_board in @message_boards%>
         <tr>
           <td>
             <table>
               <tr align="center">
                 <td>
                   <a href="<%=home_path(message_board.user.home.id)%>"><img src="<%=message_board.user.head_img%>" width="30" height="49" /></a>
                 </td>
                 <td rowspan="2">
                   <%= message_board.info.html_safe%>
                   <%if @is_admin%>
                       <p>
                         <%=link_to '删除', home_message_board_path(@current_home,message_board), confirm: '确定删除?', method: :delete %>
                       </p>
                   <%end%>
                 </td>
               </tr>
               <tr align="center">
                 <td>
                   <a href="<%=home_path(message_board.user.home.id)%>"><%=message_board.user.real_name%></a>
                 </td>
               </tr>
             </table>
           </td>
         </tr>
      <%end%>
    </table>

    <p class="module_title">
      我要留言
    </p>
      <%if session[:user]%>
        <%=form_tag home_message_boards_path(@home_id) do%>
            <table>
              <tr>
                <td>
                  内容
                </td>
               <td>
                   <%=text_area_tag 'info'%>
                  <%=hidden_field_tag 'is_master', 'true'%>
                 <%=submit_tag '确定'%>
                 <script type="text/javascript">
                     KindEditor.ready(function(K){
                         K.create('#info', {
                             "allowFileManager": false,
                             "height": 200,"width": 800,
                             "allowImageUpload": false,
                             "allowFlashUpload": false,
                             "allowMediaUpload": false,
                             uploadJson: '/kindeditor/upload',
                             fileManagerJson: '/kindeditor/filemanager'
                         });
                     });

                 </script>
               </td>
              </tr>
            </table>
        <%end%>
      <%else%>
        <p>请登录后在留言</p>
      <%end%>
  </div>
</div>