config/routes.rb
NCBlog::Application.routes.draw do

  post "/users" => "homes#create"
  resources :homes do
      resources :users
      resources :articles do
      resources :comments
    end
    resources :photo_albums do
      resources :photos
    end
    resources :message_boards
  end
  get "ajax/update_dressup"
  post "ajax/login"
  get "ajax/logout"
  get "ajax/verification_username"
  post "ajax/pa_edit"
  post "ajax/edit_cover"

   root :to => 'homes#index'

end

app/models/article.rb
#encoding : utf-8
class Article < ActiveRecord::Base
  validates_presence_of  :title,  :info,  message: '不能为空！'
  validates_length_of  :title, maximum:100, message: '长度不正确！'#minimum
  validates_length_of  :info, in: 10..3333, message: '长度不正确！'
  belongs_to :home
  has_many :comments, dependent: :destroy

  def format_date(time)
    return "#{time.year}-#{format_util time.month}-#{format_util time.day} #{format_util time.hour}:#{format_util time.min}:#{format_util time.sec}"
  end

  def  return_hot_articles

  end


  def self.return_current_page_articles(type, home_id, page)
     if type =="img"
       current_articles = Article.limit(10).offset((page.to_i-1)*10).order("created_at Desc").where("is_img=?",true).find_all_by_home_id(home_id)
     elsif type == "video"
       current_articles = Article.limit(10).offset((page.to_i-1)*10).order("created_at Desc").where("is_video=?",true).find_all_by_home_id(home_id)
     else
       current_articles = Article.limit(10).offset((page.to_i-1)*10).order("created_at Desc").find_all_by_home_id(home_id)
     end
    return current_articles
  end

  def self.count_page(type, home_id)
    if type =="img"
      length = Article.order("created_at Desc").where("is_img=?",true).find_all_by_home_id(home_id).count()
    elsif type == "video"
      length = Article.order("created_at Desc").where("is_video=?",true).find_all_by_home_id(home_id).count()
    else
      length = Article.order("created_at Desc").find_all_by_home_id(home_id).count()
    end
    if length>10
      page_temp=length%10
      if page_temp==0
        always_page =length/10
      else
        always_page= length/10+1
      end
    else
      always_page=1
    end
    return always_page
  end
  private
  def format_util(num)
     if num<10
       return "0#{num}"
     else
       return "#{num}"
    end
  end

end

app/controllers/articles_controller.rb
#encoding: utf-8
class ArticlesController < ApplicationController
  layout "show_home"
  before_filter :initialization_parameter_and_admin
  before_filter :initialization_parameter, :except => [:create, :destroy]
  def index
    type = params[:type]
    @page = params[:page]
    @page = 1 if @page.nil?
    if type =="img"
        @module_title ="图片博文"
    elsif type=="video"
      @module_title ="视频博文"
    else
      @module_title="全部博文"
     end
    @current_articles = Article.return_current_page_articles(type, @current_home.id, @page);
    @always_page = Article.count_page(type, @current_home.id)
  end

  def new
    @article = Article.new
  end

  def create

    a=params[:article]
    html_str=a[:info]
    if !(html_str  !~ /<img/)
      a[:is_img]=true
    end
   if !(html_str !~ /<embed/)
     a[:is_video]=true
   end


    a[:home_id]=params[:home_id]
    @article=Article.new(a)

     respond_to do |format|
       if  @is_admin && @article.save
         format.html{redirect_to action: 'index'}
       else
         @current_home=Home.find_by_id(params[:home_id])
         initialization_parameter_and_admin
         initialization_parameter
         format.html { render action: "new" }
         format.json { render json: @article.errors, status: :unprocessable_entity }
       end
     end
  end

  def show
    @article=Article.find_by_id(params[:id])
    @article.read_number=@article.read_number+1
    @article.save
    @comments = Comment.find_all_by_article_id(@article.id)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy if @is_admin
      respond_to do |format|
        format.html{redirect_to action: 'index'}
      end
  end

  def update

    @article = Article.find(params[:id])
    if @is_admin &&  @article.update_attributes(params[:article])
      redirect_to home_article_path(@current_home,@article)
    end

  end
  private
  def  initialization_parameter_and_admin
    @current_home=Home.find_by_id(params[:home_id])
    if @current_home
      @current_user = @current_home.user
      @is_admin=true if session[:user] && session[:user].id==@current_user.id
    else
      redirect_to homes_path
    end
  end

  def  initialization_parameter
    @dressups=Dressup.all();
    @current_dressup = @current_home.dressup
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<%=render  partial: 'homes/style_css'%>
<style type="text/css">
      #page_table tr td{
          border:  0px;
      }
</style>
<script type="text/javascript">
      $().ready(function(){
        var ptText=$("#pt").html();
        if(ptText=="视频博文"){
            $("#s3").css("fontWeight","bold");
        }else if(ptText=="图片博文"){
            $("#s2").css("fontWeight","bold");
        }else{
            $("#s1").css("fontWeight","bold");
        }
      });
</script>
<div class="bg_img">
  <p class="module_title" id="pt"><%=@module_title-%></p>
  <table width="1000" id="t">
    <tr>
      <td align="right">
          <span id="s1"><%=link_to '全部', home_articles_path(@current_home) %></span>&nbsp;&nbsp;|&nbsp;&nbsp;<img src="/images/app_img/tu.jpg"/><span id="s2"><%=link_to '含图片', home_articles_path(@current_home, type: 'img')%></span>&nbsp;&nbsp;|&nbsp;&nbsp;<img src="/images/app_img/sp.jpg"/><span id="s3"><%=link_to '含视频', home_articles_path(@current_home, type: 'video')%></span>
        <%if @is_admin%>
         &nbsp;&nbsp;|&nbsp;&nbsp;<%=link_to '发布博文', new_home_article_path%>
       <%end%>
      </td>
    </tr>
    <%for article in @current_articles%>
        <tr>
          <td>
               <div class="left_div">
                  <b>
                     <%=link_to article.title, home_article_path(@current_home,article)%>
                    <%if article.is_img?%>
                        <img src="/images/app_img/tu.jpg" />
                    <%end%>
                    <%if article.is_video?%>
                     <img src="/images/app_img/sp.jpg" />
                    <%end%>
                  </b>
               </div>
                <div class="right_div">
                    (<%=article.comments.count%>/<%=article.read_number%>)&nbsp;<%=article.format_date(article.created_at)%>
                  <%if @is_admin%>
                      <%=link_to '删除', home_article_path(@current_home,article), confirm: '确定删除?', method: :delete %>
                  <%end%>
                </div>
          </td>
        </tr>
    <%end%>
    <tr>
      <td align="right">
        <p>
          <table id="page_table">
            <tr>
              <td>
                <%=link_to '上一页', home_articles_path(@current_home, page: @page.to_i-1)  if @page.to_i!=1  %>
              </td>
              <td>
                <%=form_tag home_articles_path(@current_home) , method: 'get' do%>
                    <% str=""
                       (1..@always_page).each do |i|
                         if @page.to_i==i
                           temp="<option value='#{i}' selected='selected'>#{i}页</option>"
                         else
                           temp="<option value='#{i}' >#{i}页</option>"
                         end
                         str = str+temp
                       end%>
                    <%=select_tag 'page', str.html_safe%>
                    <%=submit_tag 'GO！'%>
                <%end%>
              </td>
              <td>
                <%=link_to '下一页', home_articles_path(@current_home, page: @page.to_i+1)  if @page.to_i!=@always_page  %>
              </td>
            </tr>
          </table>
        </p>
      </td>
    </tr>
  </table>
</div>

app/views/articles/new.html.erb
<%=render  partial: 'homes/style_css'%>

<div class="bg_img">
  <p class="module_title" id="pt">
    <%= @module_title ? @module_title : '发布博文'%>
  </p>

  <table width="1000">
    <tr>
      <td>
         <%=form_for @article, url: home_articles_path do |article|%>
            <% if @article.errors.any? %>
                <div id="error_explanation">
                  <h2><%="#{@article.errors.count}条错误" %> 博文发布失败</h2>
                    <ol type="square">
                    <% @article.errors.full_messages.each do |msg| %>
                        <li class="input_font">
                          <%if !(msg !~ /Title/) %>
                             <%=msg.gsub!('Title','标题')%>
                          <%elsif !(msg !~ /Info/)%>
                             <%=msg.gsub!('Info','内容')%>
                          <%end%>
                        </li>
                    <% end %>
                  </ol>
                </div>
            <% end %>
            <table>
              <tr>
                <td>
                  标题：
                </td>
                <td>
                  <%=article.text_field :title%>
                </td>
              </tr>
              <tr>
                <td>
                  内容：
                </td>
                <td>
                    <%= article.kindeditor :info, :width =>600, :height => 300 %>
                </td>
              </tr>
              <tr>
                <td colspan="2" align="center">
                   <%=article.submit '提交'%>
                </td>
              </tr>
            </table>
        <%end%>

      </td>
    </tr>
  </table>
</div>

app/views/articles/show.html.erb
<%=render  partial: 'homes/style_css'%>

<div class="bg_img">
  <%=form_for @article, url: home_article_path(@current_home,@article) do |article|%>
       <table>
         <tr>
           <td>
             标题：
           </td>
           <td id="title"><%=@article.title-%></td>
         </tr>
         <tr>
           <td>
               内容：
            </td>
           <td id="info"><%=@article.info.html_safe-%></td>
         </tr>
         <tr>
           <td colspan="2">
             <%if @is_admin%>
                 <script type="text/javascript">

                     function edit_textarea(event){
                         title = $("#title");
                         info = $("#info");
                         var title_str = title.html();
                         var info_str = info.html();
                         title.html("");
                         info.html("");
                         title.append($("<input name='article[title]' value='"+title_str+"'/>"));
                         info.append($("<textarea id='article_info' name='article[info]'>"+info_str+"</textarea>"));
                         KindEditor.create('#article_info', {
                             "allowFileManager": true,"height": 300,"width": 600,
                             uploadJson: '/kindeditor/upload',
                             fileManagerJson: '/kindeditor/filemanager'
                         });
                         $("#a").empty();
                         $("#div").css("display","block");
                        }

                 </script>
                 <div id="div" style="display: none;">
                    <%=article.submit '确定'%>
                    <a href="javascript: location=location;">取消</a>
                 </div>
                 <a href="javascript:edit_textarea();" id="a">编辑</a>&nbsp;&nbsp;|&nbsp;&nbsp;
                 <%=link_to '删除', home_article_path(@current_home,@article), confirm: '确定删除?', method: :delete %>
             <%end%>
           </td>
         </tr>
       </table>
    <%end%>
  <table width="1000" border="1">
    <tr>
      <th>
        评论列表
      </th>
    </tr>
    <% temp_number=0
       for comment in @comments
    temp_number+=1%>
       <tr>
         <td>
           <%=form_tag home_article_comment_path(@current_home, @article, comment), method: :put do %>
                     <table border="1" width="1000">
                             <tr>
                             <td align="center" width="10%">
                             <a href="<%=home_path(comment.user.home.id)%>"><img src="<%=comment.user.head_img%>"  width="30" height="49"/></a>
                             <br/>
                               <a href="<%=home_path(comment.user.home.id)%>"><%=comment.user.real_name%></a>
                             </td>
                             <td id="comment_info_td<%=comment.id%>"  width="90%"><%=comment.info.html_safe-%></td>
                             </tr>
                             <tr>
                             <td align="right" colspan="2">
                             <%if session[:user] && session[:user].id==comment.user_id%>
                             <a id="comment_a<%=comment.id%>" href="javascript:edit_comment('<%=comment.id%>')">编辑</a>
                             <script type="text/javascript">
                       function edit_comment(id){
                           var comment_info_td=$("#comment_info_td"+id);
                            var html_str = comment_info_td.html();
                           comment_info_td.html("<textarea id='edit_comment_info"+id+"' name='comment[info]'>"+html_str+"</textarea>");
                           KindEditor.create('#edit_comment_info'+id, {
                               "allowFileManager": false,
                               "height": 200,"width": 800,
                               "allowImageUpload": false,
                               "allowFlashUpload": false,
                               "allowMediaUpload": false,
                               uploadJson: '/kindeditor/upload',
                               fileManagerJson: '/kindeditor/filemanager'
                           });
                           $("#comment_a"+id).empty();
                           $("#comment_div"+id).css("display","block");
                       }
                     </script>
                     <div id="comment_div<%=comment.id%>" style="display: none;">
                       <%=submit_tag '确定'%>
                       <a href="javascript:location=location;">取消</a>
                     </div>
                 <%end%>
                   <%=link_to '删除', home_article_comment_path(@current_home,@article, comment), confirm: '确定删除该条评论?', method: :delete  if session[:user] && (session[:user].id==comment.user_id || @is_admin)%>
                </td>
             </tr>
           </table>
           <%end%>
         </td>
       </tr>
    <%end%>
    <tr>
      <td>
        <p align="center"><%='暂无评论' if temp_number==0%></p>
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <td>
        <p align="center">发表评论：</p>
      </td>
      <td>
        <%if session[:user]%>
        <%=form_for :comment, url: home_article_comments_path(@current_home, @article) do |comment| %>
          <%=comment.text_area 'info'%>
            <script type="text/javascript">
                KindEditor.ready(function(K){
                    K.create('#comment_info', {
                        "allowFileManager": false,
                        "height": 300,"width": 800,
                        "allowImageUpload": false,
                        "allowFlashUpload": false,
                        "allowMediaUpload": false,
                        uploadJson: '/kindeditor/upload',
                        fileManagerJson: '/kindeditor/filemanager'
                    });
                });
            </script>
            <%=comment.submit '确定'%>
        <%end%>
      <%else%>
        <p>请登录后在评论！</p>
      <%end%>
      </td>
    </tr>
  </table>
</div>

app/views/articles/update.html.erb
<script type="text/javascript">
    alert("修改失败！");
    location.href="<%=home_articles_path(@current_home)-%>"
</script>