config/routes.rb
NCBlog::Application.routes.draw do

  post "/users" => "homes#create"
  resources :homes do
      resources :users
      resources :articles do
      resources :comments
    end
    resources :photo_albums do
      resources :photos
    end
    resources :message_boards
  end
  get "ajax/update_dressup"
  post "ajax/login"
  get "ajax/logout"
  get "ajax/verification_username"
  post "ajax/pa_edit"
  post "ajax/edit_cover"

   root :to => 'homes#index'

end

app/models/home.rb
#encoding: utf-8
class Home < ActiveRecord::Base
  belongs_to :user
  belongs_to :dressup
  has_many :articles
  has_many :photo_albums
  has_many :comments
  has_many :message_boards
  def  self.create_home_relevance_user(user)
    home=Home.new(user: user, title: "#{user.real_name}的家")
    home.save
  end

  #存入访客
  def self.add_visitor_list(home, session)
    home_id=session[:user].home.id
     if session[:user] && home_id != home.id
        home_arr=return_arr(home)
      if home_arr
          if   home_arr.include?(home_id.to_s)
            home_arr.each do |ha|
                if ha==home_id.to_s
                  home_arr.delete(ha)
                  break
                end
            end
          elsif home_arr.length>=20
            home_arr.delete(home_arr[0])
          end
      else
        home_arr=[]
       end
       home_arr << home_id
       home.visitor_list= home_arr.join(",")
       return home.save
     end
    false
  end

  #取出访客
  def self.select_visitor_list(home)
      home_arr=return_arr(home)
      home_list=[]
      if home_arr
       home_arr.reverse.each do  |ha|
           home_list << Home.find_by_id(ha);
       end
    end
    return home_list
  end

  private
  def self.return_arr(home)
      home_arr=[]
     home_arr=home.visitor_list.split(",")  if home.visitor_list
  end

end

app/controllers/homes_controller.rb
#encoding: utf-8
class HomesController < ApplicationController
  # GET /homes
  # GET /homes.json
  layout "login", :except => [:new, :show]
  def index
    @new_user=User.limit(10).order("created_at DESC").all()
  end

  # GET /homes/2
  # GET /homes/2.json
  def show
    @current_home=Home.find_by_id(params[:id])
    if @current_home
      @current_user = @current_home.user
      @current_articles = Article.order("updated_at Desc").limit(10).find_all_by_home_id(@current_home.id)
      @comments = Comment.order("updated_at Desc").limit(5).find_all_by_home_id(@current_home.id)
      @current_dressup = @current_home.dressup
      @dressups=Dressup.all();
      @is_admin=true if session[:user] && session[:user].id==@current_user.id
      Home.add_visitor_list(@current_home, session) if session[:user]
      @home_list=Home.select_visitor_list(@current_home)
      @imgs = @current_home.photo_albums.first if  @current_home.photo_albums
      @message_boards = MessageBoard.limit(5).order("created_at DESC").find_all_by_home_id(@current_home.id)
      render layout: "show_home"

    else
      redirect_to homes_path
    end


  end

  # GET /homes/new
  # GET /homes/new.json
  #注册
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /homes/2/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  #注册后创建
  def create
    u=params[:user]
  u[:real_name]=u[:username]


  @user = User.new(u)

  respond_to do |format|
    if !(u[:password]  !~  /^[\da-zA-z]{6,12}$/) && @user.save
      session[:user]=User.create_full_user(@user)
      format.html
    else
      @user.errors[:password]='格式不正确'  if !(u[:password]  !~  /^[\da-zA-z]{6,12}$/)
      format.html { render action: "new" }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end



end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_login.html.erb
<div id="comments">
  <%if session[:user]%>
      <%=link_to '首页', homes_path%>
      <span>欢迎用户=<%=link_to session[:user].username, home_path(session[:user]) %>=光临</span>
      <%=link_to '注销', controller: "ajax", action: "logout" %>
  <%else%>
      <table>
        <tr>
          <td>

            <%=form_tag "/ajax/login", remote: true, method: 'post' do%>
                <%=link_to '返回首页', homes_path%>
                用户名：<%=text_field_tag 'username' %>
                密&nbsp;&nbsp;&nbsp;&nbsp;码：<%=password_field_tag 'password'%>
                <%=submit_tag '登录'%>
            <%end%>
          </td>
          <td>
            没有账号？<%=link_to '点我注册', new_home_path %>
          </td>
        </tr>
      </table>
  <%end%>
</div>

app/views/homes/_style_css.html.erb
<style type="text/css">
    /*body颜色*/
   body{
       <%if @current_dressup.background[0]=='#'%>
         background-color:<%=@current_dressup.background%>;
       <%else%>
       background-image: url("<%=@current_dressup.background%>");
       <%end%>
   }
    /*字体颜色*/
   *{
       color: <%=@current_dressup.font_color%>;
   }
   /*背景图*/
  .bg_img{
      background-image: url("<%=@current_dressup.background_img%>");
  }
  /*导航背景*/
 .menu_img{
     background-image: url("<%=@current_dressup.menu_bg%>");
     width:1000px;
     height: 45px;
 }
 /*模块背景*/
 .module_img{
   background-image: url("<%=@current_dressup.module_bg%>");
 }
/*模块标题背景*/
 .module_title{
     background-image: url("<%=@current_dressup.module_title_bg%>");
     margin-top: 0;
     height: 20px;
     font-size: 18px;
 }
/*文章上部分*/
 .article_up{
     background-image: url("<%=@current_dressup.article_bg_up%>");
     width: 620px;
     height: 80px;
 }
/*文章下部分*/
 .article_down{
     background-image: url("<%=@current_dressup.article_bg_down%>");
     width: 620px;
     border-top:  1px #000000 solid;
 }
 /*上log*/
 .up_scene{
     background-image: url("<%=@current_dressup.up_scene%>");
     width:1000px;
     height: 214px;
 }
 /*下end*/
 .down_scene{
     background-image: url("<%=@current_dressup.down_scene%>");
     width:1000px;
     height: 200px;
 }
  /*a标签样式*/
   a:link{text-decoration:none;color:<%=@current_dressup.a_before%>;}
   a:visited{text-decoration:none;color:<%=@current_dressup.a_before%>;}
   a:hover{text-decoration:underline;color:<%=@current_dressup.a_after%>;}

</style>

app/views/homes/create.html.erb
<script type="text/javascript">
    var num=5;
    var time;
    function auto_time(){
        num--;
        $("#sp").html(num)
        time=setTimeout(auto_time,1000);
        if(num<=0){
            location.href="/homes"
            clearTimeout(time);
        }
    }
    auto_time();
</script>
<div style="width:300px" class="default">
  <%=@user.username%>注册成功,<span id="sp">5</span>秒后自动返回！<br/>
  <%=link_to '或者点击我', homes_path%>
</div>

app/views/homes/index.html.erb
<div style="width: 1000px;height:600px">

    <link href="/css/templatemo_style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/css/contentslider.css" />
    <script type="text/javascript" src="/js/contentslider.js"></script>

  <div id="templatemo_header_panel">
  <div id="templatemo_header_section">
    <div id="templatemo_title_section">
      NC BLOG
    </div>
    <div id="templatemo_search_section">
      <form method="get" action="#">
        <input type="radio" name="search" value="thissite" />按用户名 <input type="radio" name="search" value="theweb" checked="checked" />按博客名<br />
        <input type="text" name="q" size="10" id="searchfield" title="searchfield" />
        <input type="submit" name="Search" value="搜索"  id="searchbutton" onclick="alert('对不起我的功能还没有实现！');" />
      </form>
    </div>
  </div>
</div>

  <div id="templatemo_menu_panel">
    <div id="templatemo_menu_section">
      <ul>
        <li><a href="<%=homes_path%>"  class="current">首页</a></li>
        <li><a href="javascript:alert('木有新鲜事！');">新鲜事</a></li>
        <li><a href="javascript:alert('本网站是本人闲暇时间作品。\n如有BUG请见谅。其他提示请按<帮助>');">关于</a></li>
        <li><a href="javascript:alert('有事找QQ：353284782');">帮助</a></li>
      </ul>
    </div>
  </div> <!-- end of menu -->

  <div id="templatemo_content_container">
    <div id="templatemo_content">
      <div id="templatemo_content_left">

        <div class="templatemo_post">
          <h1>NC新闻</h1>

          <div id="slider2" class="sliderwrapper">
            <div class="contentdiv"><img src="images/templatemo_image_2.jpg" alt="image" /></div>
            <div class="contentdiv"><img src="images/templatemo_image_3.jpg" alt="image" /></div>
            <div class="contentdiv"><img src="images/templatemo_image_4.jpg" alt="image" /></div>
          </div>

          <div id="paginate-slider2" class="pagination">

            <a href="#" class="toc">1</a> <a href="#" class="toc anotherclass">2</a> <a href="#" class="toc">3</a>
          </div>
          <script type="text/javascript">

              featuredcontentslider.init({
                  id: "slider2",  //id of main slider DIV
                  contentsource: ["inline", ""],  //Valid values: ["inline", ""] or ["ajax", "path_to_file"]
                  toc: "markup",  //Valid values: "#increment", "markup", ["label1", "label2", etc]
                  nextprev: ["Previous", "Next"],  //labels for "prev" and "next" links. Set to "" to hide.
                  revealtype: "click", //Behavior of pagination links to reveal the slides: "click" or "mouseover"
                  enablefade: [true, 0.2],  //[true/false, fadedegree]
                  autorotate: [true, 3000],  //[true/false, pausetime]
                  onChange: function(previndex, curindex){  //event handler fired whenever script changes slide
                      //previndex holds index of last slide viewed b4 current (1=1st slide, 2nd=2nd etc)
                      //curindex holds index of currently shown slide (1=1st slide, 2nd=2nd etc)
                  }
              })

          </script>
        </div> <!-- end of one post -->

        <div class="templatemo_post">
          <div class="post_title">
            热门博文
            <div class="post_info">
              测试数据<a href="#" target="_parent">-测试-</a>-测试数据-<a href="#">-测试数据-.</a>
            </div>
          </div>

          <div class="post_body">
            <img src="images/templatemo_image_1.jpg" alt="Free CSS" />
            <p>我们都是测试数据！</p>
            <p>我们都是测试数据！</p>
            <p>我们都是测试数据！</p>
          </div>
          <div class="post_comment">
            <a href="#">查看全文</a>
          </div>
        </div> <!-- end of post two -->


      </div> <!-- end of content left -->

      <div id="templatemo_content_right">

        <div class="templatemo_right_section">
          <h2>联系客服</h2>
            <a target=blank href=tencent://message/?uin=353284782Menu=yes><img border="0" src='http://wpa.qq.com/pa?p=1:17421778:13' alt="这里给我留言"></a>
          <p>客服帮助(绝不24小时在线)</P>
        </div>


        <div class="templatemo_right_section">
          <h2>最新注册用户</h2>
          <ul>
            <%for user in @new_user%>
                <li style="clear: left;"><a href="<%=home_path(user.home)%>"><%=user.real_name%></a></li>
            <%end%>
          </ul>
        </div>

        <div class="templatemo_right_section">
          <h2>热门话题</h2>
          <ul>
            <li>XXXXXX <a href="#">XXXXXXXXXXXXXXXXXX</a></li>
            <li>XXXXXX <a href="#">XXXXXXXXXXXXXXXXXX</a></li>
            <li>XXXXXX <a href="#">XXXXXXXXXXXXXXXXXXX</a></li>
            <li>XXXXXX <a href="#">XXXXXXXXXXXX</a></li>
            <li>XXXXXX <a href="#">XXXXXXXXXXXX</a></li>
          </ul>
        </div>

      </div> <!-- end of right content -->
    </div> <!-- end of content -->
  </div> <!-- end of content container -->

  <div id="templatemo_bottom_panel">
    <div id="templatemo_bottom_section">

      <div class="templatemo_bottom_section_content">
        <h3>联盟军团</h3>
        <p>联盟军团1号</p>
        <p>联盟军团2号</p>
        <p>联盟军团3号</p>
      </div>

      <div class="templatemo_bottom_section_content">
        <h3>合作伙伴</h3>
        <ul>
          <li><a href="#" target="_parent">合作伙伴1号</a></li>
          <li><a href="#" target="_parent">合作伙伴2号</a></li>
          <li><a href="#" target="_parent">合作伙伴3号</a></li>
          <li><a href="#" target="_parent">合作伙伴4号</a></li>
          <li><a href="#" target="_parent">合作伙伴5号</a></li>
        </ul>
      </div>

      <div class="templatemo_bottom_section_content">
        <h3>广告</h3>
        <ul>
          <li><a href="#">广告1</a></li>
          <li><a href="#">广告2</a></li>
          <li><a href="#">广告3</a></li>
          <li><a href="#">广告4</a></li>
        </ul>
      </div>
    </div> <!-- end of templatemo bottom section -->
  </div> <!-- end of templatemo bottom panel -->
  <!--  HTML CSS Template Designed by w w w . t e m p l a t e m o . c o m  -->
  <div id="templatemo_footer_panel">
    <div id="templatemo_footer_section">
      Copyright © 2024 <a href="#">版权所有</a> | 博酷在线 <a title="bocoo" href="#" >翻版必究</a>
    </div>
  </div>
</div>

app/views/homes/new.html.erb
<link href="/css/templatemo_style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/css/contentslider.css" />
<script type="text/javascript" src="/js/contentslider.js"></script>
<style type="text/css">
   table tr td{
       text-align: center
   }
</style>
<script type="text/javascript">
  $().ready(function (){
      $("#user_username").blur(function(){
          chageUsername($(this));
      });
      $("#user_password").blur(function(){
          chagePWD($(this));
      });
      $("#repeat_password").blur(function(){
          chageAPWD($(this));
      });
      $("#user_username").blur(function(){
          chageUsername($(this));
      });
      $("#user_email").blur(function(){
          chageEmail($(this));
      });
  });

  //返回
    function clickBack(){
        history.go(-1);
    }
</script>
<div id="templatemo_header_panel">
  <div id="templatemo_header_section">
    <div id="templatemo_title_section">
      NC BLOG
    </div>
    <div id="templatemo_search_section">
      <form method="get" action="#">
        <input type="radio" name="search" value="thissite" />按用户名 <input type="radio" name="search" value="theweb" checked="checked" />按博客名<br />
        <input type="text" name="q" size="10" id="searchfield" title="searchfield" />
        <input type="submit" name="Search" value="搜索"  id="searchbutton" onclick="alert('对不起我的功能还没有实现！');" />
      </form>
    </div>
  </div>
</div>
<div class="default" align="center">

  <h1>注册用户</h1>
    <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "错误") %> 注册失败</h2>

              <ul>
                <% @user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

           <table align="center">
             <tr>
               <td>
                 <%= f.label '用户名' %>
               </td>
               <td>
                 <%= f.text_field :username %><br/>
                 <span id="s1">&nbsp;</span>
               </td>
            </tr>
             <tr>
               <td>
                 <%= f.label '密码' %>
               </td>
               <td>
                 <%= f.password_field :password %><br/>
                 <span id="s2">&nbsp;</span>
               </td>
             </tr>
             <tr>
               <td>
                 <%= f.label '重复密码'%>
               </td>
               <td>
                 <%= password_field_tag :repeat_password %><br />
                 <span id="s3">&nbsp;</span>
               </td>
             </tr>
             <tr>
               <td>
                 <%= f.label '性别' %>
               </td>
               <td>
                 男：<%= f.radio_button :sex, 1, checked: "checked"%>&nbsp;&nbsp;&nbsp;&nbsp;
                 女：<%= f.radio_button :sex, 0 %>
               </td>
             </tr>
             <tr>
               <td>
                 <%= f.label '邮箱' %>
               </td>
               <td>
                 <%= f.text_field :email %><br/>
                 <span id="s4">&nbsp;</span>
               </td>
             </tr>
             <tr>
               <td colspan="2">
                 <%= f.button '注册', type: 'button', onclick: 'submitAll();' %>&nbsp;&nbsp;|&nbsp;&nbsp;
                 <%= link_to '返回', "#", onclick: "clickBack();" %>
               </td>
             </tr>
           </table>
      <br/>
      <br/>
    <% end %>
  <div id="templatemo_bottom_panel">
    <div id="templatemo_bottom_section">

      <div class="templatemo_bottom_section_content">
        <h3>联盟军团</h3>
        <p>联盟军团1号</p>
        <p>联盟军团2号</p>
        <p>联盟军团3号</p>
      </div>

      <div class="templatemo_bottom_section_content">
        <h3>合作伙伴</h3>
        <ul>
          <li><a href="#" target="_parent">合作伙伴1号</a></li>
          <li><a href="#" target="_parent">合作伙伴2号</a></li>
          <li><a href="#" target="_parent">合作伙伴3号</a></li>
          <li><a href="#" target="_parent">合作伙伴4号</a></li>
          <li><a href="#" target="_parent">合作伙伴5号</a></li>
        </ul>
      </div>

      <div class="templatemo_bottom_section_content">
        <h3>广告</h3>
        <ul>
          <li><a href="#">广告1</a></li>
          <li><a href="#">广告2</a></li>
          <li><a href="#">广告3</a></li>
          <li><a href="#">广告4</a></li>
        </ul>
      </div>
    </div> <!-- end of templatemo bottom section -->
  </div> <!-- end of templatemo bottom panel -->
  <!--  HTML CSS Template Designed by w w w . t e m p l a t e m o . c o m  -->
  <div id="templatemo_footer_panel">
    <div id="templatemo_footer_section">
      Copyright © 2024 <a href="#">版权所有</a> | 博酷在线 <a title="bocoo" href="#" >翻版必究</a>
    </div>
</div>
</div>

app/views/homes/show.html.erb
<%=render  partial: 'homes/style_css'%>
<style type="text/css">
    #slider {
        width: 200px; /* important to be same as image width */
        height: 300px; /* important to be same as image height */
        position: relative; /* important */
        overflow: hidden; /* important */
    }
    #slider img{
        border: 0px;
    }

    #sliderContent {
        width: 200px; /* important to be same as image width or wider */
        position: absolute;
        top: 0;
        margin-left: 0;
    }
    .sliderImage {
        float: left;
        position: relative;
        display: none;
    }
    .sliderImage span {
        position: absolute;
        font: 12px/15px Arial, Helvetica, sans-serif;
        padding: 5px 5px;
        margin-left: -90px;
        width: 200px;
        background-color: #000;
        filter: alpha(opacity=70);
        -moz-opacity: 0.7;
        -khtml-opacity: 0.7;
        opacity: 0.7;
        color: #fff;
        display: none;
    }
    .clear {
        clear: both;
    }
    .sliderImage span strong {
        font-size: 13px;
    }
    .top {
        top: 0;
        left: 0;
    }
    .bottom {
        bottom: 0;
        left: 0;
    }
</style>
<script type="text/javascript" src="/js/s3Slider.js"></script>
<style type="text/css">
  .format_div{
      width: 50px; height: 20px; overflow:hidden;
  }
</style>
<script type="text/javascript">
  $().ready(function(){
      $('#slider').s3Slider({
          timeOut: 5000
      });
  });
</script>
<div class="bg_img">
     <table>
       <tr>
         <td>
           <div class="left_div">
             <!--其他信息-->
              <div class="module_img" style="width: 200px;">
                <!--头像-->
               <p class="module_title">
                    个人资料
               </p>
               <img src="<%=@current_user.head_img%>"  width="200" height="322" />
                <h4 align="center" style="margin-top: 5px;margin-bottom: 5px;">
                     <%=@current_user.real_name%>
                </h4>
                <ol type="disc">
                  <li>
                    等级：<%=@current_home.rank%>
                  </li>
                  <li>
                    积分：<%=@current_home.exp%>
                  </li>
                  <li>
                    访问人数：<%=@current_home.visit%>
                  </li>
                  <li>
                    关注人气：<%=@current_home.attention%>
                  </li>
                </ol>
              </div>

             <div class="module_img">
               <!--图片播放器-->
               <p class="module_title">
                 图片播放器
               </p>

                   <%if @imgs && @imgs.photos.length>0%>
                     <div id="slider" style="width: 200px;height: 222px">
                       <ul id="sliderContent">
                         <%for img in @imgs.photos%>
                             <li class="sliderImage">
                               <a href="javascript:return false;" ><img src="<%=img.p_path%>" style="margin-left: -90px" width="200" height="222" /></a>
                               <span class="top" ><strong><%=img.p_name%></strong><br /><%=img.info%></span>
                             </li>
                         <%end%>
                        <div class="clear sliderImage"></div>
                       </ul>
                     </div>
                 <%else%>
                   <div class="m_wh" align="center">
                     主人暂无设置预览图片
                   </div>
                 <%end%>

             </div>

             <div class="module_img">
               <!--音乐播放器-->
               <p class="module_title">
                 音乐播放器
               </p>

               <div class="m_wh" align="center">
                     暂无音乐
               </div>
             </div>

             <div class="module_img">
               <!--评论列表-->
               <p class="module_title">
                 评论列表
               </p>


               <%if @current_home.comments.length>0%>
                   <div>
                     <table border="1">
                       <%for comment in @comments%>
                       <tr align="center">
                         <td>
                           <a href="<%=home_path(comment.home_id)%>" alt="<%=comment.user.real_name%>"><img src="<%=comment.user.head_img%>" width="30" height="49" /></a>
                         </td>
                         <td rowspan="2">
                           <div style="width: 130px;height: 70px;white-space:normal; overflow:hidden;">
                             <a href="<%=home_article_path(comment.home_id, comment.article_id)%>"><%=comment.info.html_safe%></a>
                           </div>
                         </td>
                       </tr>
                           <tr>
                             <td>
                               <div class="format_div">
                               <a href="<%=home_path(comment.home_id)%>" alt="<%=comment.user.real_name%>"><%=comment.user.real_name%></a>
                               </div>
                             </td>
                           </tr>
                       <%end%>
                     </table>
                   </div>
               <%else%>
                   <div class="m_wh" align="center">
                     暂无评论
                   </div>
               <%end%>
             </div>

             <div class="module_img">
               <!--留言列表-->
               <p class="module_title">
                留言
               </p>
               <%if @message_boards.length > 0 %>
                   <%for message_board in @message_boards%>
                    <table border="1">
                       <tr align="center">
                         <td style="width: 30px;">
                           <a href="<%=home_path(message_board.user.home)%>"><img src="<%=message_board.user.head_img%>" width="30" height="49"/></a>
                         </td>
                         <td rowspan="2" style="width: 130px;height: 70px;white-space:normal; overflow:hidden;">
                           <a href="<%=home_message_boards_path(@current_home)%>"><%=message_board.info.html_safe%></a>
                         </td>
                       </tr>
                       <tr align="center">
                         <td>
                           <div class="format_div">
                             <a href="<%=home_path(message_board.user.home)%>"><%=message_board.user.real_name%></a>
                           </div>

                         </td>
                       </tr>
                     </table>
                   <%end%>
               <%else%>
                 <div class="m_wh" align="center">
                   暂无留言
                 </div>
               <%end%>
             </div>

             <div class="module_img">
               <!--访客列表-->
               <p class="module_title">
                 访客列表
               </p>
               <% if  @home_list.length>0%>
                   <table width="200">
                     <%
                          temp=0
                        for hl in @home_list
                          temp+=1%>
                        <%if temp == 1%>
                             <tr align="center">
                               <td class="format_div">
                                 <a href="<%=home_path(hl)%>"><img src="<%=hl.user.head_img%>" width="30" height="49"/><br/>
                                  <%=hl.user.real_name%></a>
                               </td>
                        <%else temp == 2
                        temp==0%>
                             <td class="format_div">
                               <a href="<%=home_path(hl)%>"><img src="<%=hl.user.head_img%>" width="30" height="49"/><br/>
                               <%=hl.user.real_name%></a>
                             </td>
                            </tr>
                        <%end%>
                     <%end%>
                   </table>
               <%else%>
                 <div class="m_wh" align="center">
                   暂无访客
                 </div>
               <%end%>
             </div>
           </div>

           <div class="right_div" style="padding-left: 80px;">
                <!--博文目录-->
                 <p class="module_title">
                   最新博文
                 </p>
                 <div>
                   <%for article in @current_articles%>
                     <div class="article_up">
                         <table>
                           <tr>
                             <td>
                               <h2  style="color: #000000;">标题：<%=article.title%></h2><span  style="color: #000000;">(<%=article.format_date(article.created_at)%>)</span>
                            </td>
                           </tr>
                         </table>
                     </div>
                     <div class="article_down">
                       <p  style="color: #000000;">
                         正文：
                       </p>
                        <div name="article_div" style="width: 580px;margin: auto;word-wrap:break-word;color: #000000;" >
                          <%= truncate(strip_tags(article.info), :length => 100)%>
                        </div>
                       <p>
                        <table width="580">
                          <tr>
                            <td style="color: #000000;">
                              阅读:(<%=article.read_number%>)评论(<%=article.comments.count%>)转载(<%=article.reprint_number%>)
                            </td>
                            <td style="color: #000000;" align="right">
                              <%=link_to '<<阅读全文', home_article_path(@current_home,article)%>
                            </td>
                          </tr>
                        </table>
                       </p>
                     </div>
                       <br/>
                    <%end%>
                 </div>
           </div>
         </td>
       </tr>
     </table>
</div>